-- INSERT INTO `aps`.`ship_forecast` (`ID`, `SHIP_NAME`, `SHIP_NO`, `IN_OUT_TRADE`, `LOAD_QTY`, `EXCEPT_ARRIVE_TIME`, `CARGO_PROCEDURE`, `SHIP_PROCEDURE`, `SHIP_LENGTH`, `SHIP_WIDTH`, `DRAFT`, `CAPACITY_PER_HOUR`, `LOAD_UNLOAD`) VALUES (1, '山东大德', 'shandongdade', 1, 10000, '2024-09-02 17:00:52', '1', '1', 300.00, 60.00, '15', 1000.00, 1);
-- INSERT INTO `aps`.`ship_forecast` (`ID`, `SHIP_NAME`, `SHIP_NO`, `IN_OUT_TRADE`, `LOAD_QTY`, `EXCEPT_ARRIVE_TIME`, `CARGO_PROCEDURE`, `SHIP_PROCEDURE`, `SHIP_LENGTH`, `SHIP_WIDTH`, `DRAFT`, `CAPACITY_PER_HOUR`, `LOAD_UNLOAD`) VALUES (2, '第一永恒', 'firstImmortal', 2, 20000, '2024-09-02 17:00:57', '1', '1', 270.00, 70.00, '12', 1200.00, 2);




-- 泊位数据
INSERT INTO `aps`.`berth_info` (`ID`, `BERTH_NO`, `BERTH_NAME`, `FLOW_LOAD`, `FLOW_UNLOAD`, `MOVE_LOAD`, `MOVE_UNLOAD`, `BERTH_LENGTH`, `AVAILABLE`) VALUES (1, 'D1', 'D1', 0, 1, 0, 0, 510.00, 1);
INSERT INTO `aps`.`berth_info` (`ID`, `BERTH_NO`, `BERTH_NAME`, `FLOW_LOAD`, `FLOW_UNLOAD`, `MOVE_LOAD`, `MOVE_UNLOAD`, `BERTH_LENGTH`, `AVAILABLE`) VALUES (2, 'D2', 'D2', 0, 1, 1, 1, 357.00, 1);
INSERT INTO `aps`.`berth_info` (`ID`, `BERTH_NO`, `BERTH_NAME`, `FLOW_LOAD`, `FLOW_UNLOAD`, `MOVE_LOAD`, `MOVE_UNLOAD`, `BERTH_LENGTH`, `AVAILABLE`) VALUES (3, 'D3', 'D3', 0, 1, 1, 1, 342.00, 1);
INSERT INTO `aps`.`berth_info` (`ID`, `BERTH_NO`, `BERTH_NAME`, `FLOW_LOAD`, `FLOW_UNLOAD`, `MOVE_LOAD`, `MOVE_UNLOAD`, `BERTH_LENGTH`, `AVAILABLE`) VALUES (4, 'D4', 'D4', 1, 1, 1, 1, 357.00, 1);
INSERT INTO `aps`.`berth_info` (`ID`, `BERTH_NO`, `BERTH_NAME`, `FLOW_LOAD`, `FLOW_UNLOAD`, `MOVE_LOAD`, `MOVE_UNLOAD`, `BERTH_LENGTH`, `AVAILABLE`) VALUES (5, 'D5', 'D5', 1, 1, 1, 1, 241.60, 1);
